name: google-only titles
url: https://www.google.com/search?q=%2Crdo&amp;sxsrf=APq-WBtZmeOMzH8FSlTk-cTQjlHI0DeiDA%3A1644755594870&amp;ei=ivoIYta-NPWC9u8Pk7mbiA8&amp;ved=0ahUKEwjWq-WH2Pz1AhV1gf0HHZPcBvEQ4dUDCA4&amp;uact=5&amp;oq=%2Crdo&amp;gs_lcp=Cgdnd3Mtd2l6EAMyBwgjELECECcyBAgAEAoyCggAELEDEIMBEAoyCggAELEDEIMBEAoyBAgAEAoyBAgAEAoyCggAELEDEIMBEAoyBAgAEAoyBAgAEAoyBAgAEAo6CAgAEIAEELADOgkIABCwAxAHEB46BwgAELADEB46BAgjECc6BwgAEIAEEAo6CQgAEIAEEAoQAToFCAAQgAQ6BwgjEOoCECc6BggjECcQEzoLCAAQsQMQChABEEM6CwguEIAEELEDEIMBOhEILhCABBCxAxCDARDHARDRAzoECC4QQzoECAAQQzoHCAAQsQMQCjoNCAAQsQMQChABEEMQKjoLCAAQgAQQsQMQgwE6BwgAELEDEEM6CAgAEIAEELEDOgUILhCABEoECEEYAUoECEYYAFCECFjvGmCqHGgCcAB4AYABrAGIAcUIkgEDMC43mAEAoAEBsAEKyAEKwAEB&amp;sclient=gws-wiz
useTor: false
maxUrls: 5
allPosts:
  selector: "#rso &gt; div:nth-child(6) &gt; div &gt; div.NJo7tc.Z26q7c.jGGQ5e &gt; div"
params:
  title:
    selector: a &gt; h3 &gt; span
    regex: /\/\/(?:)\/\//
  content:
    selector: a &gt; h3 &gt; span
    regex: /\/\/(?:)\/\//
  date:
    selector: a &gt; h3 &gt; span
    regex: /\/\/(?:)\/\//
  url:
    selector: a &gt; h3 &gt; span
    regex: /\/\/(?:)\/\//
