name: madlan
url: https://www.madlan.co.il/
useTor: false
maxUrls: 5
allPosts:
  selector: body
params:
  title:
    selector: .css-19tpcfu .eu6esji3
    regex: /\/(?:)\//
  content:
    selector: .css-1i00gl6 .e1sx3tzs17
    regex: /\/(?:)\//
  author:
    selector: .css-1i00gl6 .e1sx3tzs17
    regex: /\/(?:)\//
  date:
    selector: div.css-1yo09r9.eu6esji13 &gt; div &gt; div
    regex: /\/(?:)\//
