name: Stronghold-momo
url: http://strongerw2ise74v3duebgsvug4mehyhlpa7f6kfwnas7zofs3kov7yd.onion/all
useTor: true
maxUrls: 5
allPosts:
  selector: .col-sm-12
params:
  content:
    selector: h4
    regex: /(?:)/
  title:
    selector: ol
    regex: /(?:)/
  author:
    selector: .col-sm-6
    regex: /(?<=(\w+\s){2})(\w+)/
  date:
    selector: .col-sm-6
    regex: /\d+\s[a-zA-Z]+\s\d+,\s\d+:\d+:\d+\s[a-zA-Z]+/
