name: madlan
url: https://www.madlan.co.il/
useTor: false
maxUrls: 5
allPosts:
  selector: "#root > div"
params:
  title:
    selector: div.css-dywgfi.eu6esji1 > div
    regex: /(?:)/
  rooms:
    selector: div.css-1yo09r9.eu6esji12 > div:nth-child(1)
    regex: /(?:)/
  author:
    selector: .col-sm-6
    regex: /(?<=(\w+\s){2})(\w+)/
  date:
    selector: .col-sm-6
    regex: /\d+\s[a-zA-Z]+\s\d+,\s\d+:\d+:\d+\s[a-zA-Z]+/
